sudo: required
cache: npm
node_js: 
- "stable"
services: docker
script: 
- npm install
- npm test
- npm run build
- docker build . -t gcr.io/maximal-brace-238118/frontend:latest
- docker container list


